build:
  prefetch: true
ghc-options:
  "$everything": -split-sections
allow-newer: true
setup-info:
  ghc:
    linux64-nopie:
      8.2.1.20171108:
        url: https://downloads.haskell.org/~ghc/8.2.2-rc3/ghc-8.2.1.20171108-x86_64-deb8-linux.tar.xz
