version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    environment:
      - NINJA_J: 2
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u terrorjack -p $DOCKER_PASS
          docker build -t terrorjack/rakuen:nightly-2017-11-10 .
          docker push terrorjack/rakuen:nightly-2017-11-10
