version: 2
jobs:
  build:
    context: org-global
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build --squash -t terrorjack/rakuen:$CIRCLE_TAG .
          docker login -u terrorjack -p $DOCKER_PASS
          docker push terrorjack/rakuen:$CIRCLE_TAG
